version: "3.3"

services:

  menu-api:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: menu_api
    volumes:
      - ./src:/app/src
      - ./spec:/app/spec
    env_file:
      - .env
    ports:
    - 8000:8000

  db:
    container_name: menu_db
    image: mysql:5.7
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
    - 3306:3306

  phpmyadmin:
    container_name: menu_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
    ports:
      - 8090:80
